mode: paper

binance:
  api_key: "your_api_key"
  api_secret: "your_api_secret"
  testnet_url: "https://testnet.binance.vision/api"
  live_url: "https://api.binance.com/api"

trading:
  symbol: "BTCUSDT"
  quantity: 0.001
  risk_reward_ratio: 2
  atr_period: 14
  breakout_lookback: 10
  interval: "1h"
  signal_check_interval_minutes: 60

email:
  from: "your_email@gmail.com"
  to: "your_email@gmail.com"
  password: "your_gmail_app_password"
